# Generated by Django 6.0.3 on 2026-04-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='data_inicio',
            field=models.DateField(),
        ),
    ]
