# Generated by Django 6.0.3 on 2026-04-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_perfil_foto_alter_experiencia_data_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='curriculo',
            field=models.FileField(blank=True, null=True, upload_to='curriculos/'),
        ),
    ]
