# Generated by Django 6.0.3 on 2026-04-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_perfil_curriculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(default='texto padrão', upload_to='projetos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
    ]
