# Generated by Django 6.0.3 on 2026-04-08 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_projeto_descricao_projeto_imagem_projeto_ordem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='link_github',
            new_name='link_repositorio',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='link_linkedin',
        ),
    ]
