# Generated by Django 6.0.3 on 2026-04-09 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_rename_link_github_projeto_link_repositorio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='link_site',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
